### ISSUE TITLE
Add Analysis Product

### ISSUE THREAD

**Issue by EugeneAgyemang** [EugeneAgyemang/FPIS#19]
A user wants to add a new Analysis Product for analysis.

Acceptance Criteria
Implement the design for the add Analysis Product UI
Implement the logic to add a new Analysis Product
Write the necessary unit test

Implementation Note
Use a standard design for the UI

**Comment by denkyipatrick** [comment]
Please find my work on this link https://github.com/EugeneAgyemang/FPIS/pull/47.

Since we cannot directly add an `analysis item`, I had to instead add `analysis product`. `Analysis Water` will be added later.
