### ISSUE TITLE
Create Material Procurement 

### ISSUE THREAD

**Issue by scottondesign** [EugeneAgyemang/FPIS#30]
A user wants to Add Material Procurement Item   
Acceptance Criteria
-	Implement the design for Material Procurement Item  
-	Implement the logic to Add Material Procurement Item  
-	Write the necessary Unit Test

Implementation Note
Use a standard Design for the UI

Features:
-	DML (Insert, Update and Delete Data) Features – Material Procurement
-	DQL (Select) Features – For Reporting 
-	Manages the state of the Material types (Shea nuts)
-	{Receiving} Date of Receipt, Location of Storage, Supplier, Truck Number, Quantity, %Moisture, FFA, Remarks (ref Shea nut Receiving & Releasing file)
-	{Releasing} Date, %Moisture, Fat Content, FFA, Remarks, Location Remarks (ref Shea nut Receiving & Releasing file)
-	Truck Number can not be repeated same day for RECEIVING (A message box “Same truck cannot be received same day”)
-	%Moisture Above required standard for RECEIVING ( A Message Box “ Moisture too High to be received”)

**Comment by MartyOfMCA** [comment]
The attached PR has all the code changes.

257b7c7f68cb60c6838d9fac0580084935f8d037 contains the migration that updates the database to include the Lot number to the MaterialProcurement model.


e7c72f01a058e7dc74c7fd1098c7876381460786 also contains the following changes:
* The material procurement receiving screen has widgets moved around to include the Lot
* Users can now enter the unit for the material procured
* Validations are added for the new field Lot as well as the Unit field


b8cba435fbca57a369c48de1e6c9639dbf19e739 also has a feature called the sample request helper.
* Users can now view help on how to provide details on materials procured
