### ISSUE TITLE
Fix LoginTest.cs unit test

### ISSUE THREAD

**Issue by MartyOfMCA** [EugeneAgyemang/FPIS#39]
Resolve the bug that prevents the FPIS solution to fail when building

**Comment by MartyOfMCA** [comment]
I have added unit tests to check the following functions in `Login.cs`

* `UserProvidedData()`
* `ResetFields()`

![image](https://user-images.githubusercontent.com/104218489/214191525-02119a95-b9f7-44e5-bbec-729a545372fa.png)


Would test the last function after PR#20 is merged

**Comment by MartyOfMCA** [comment]
Also added the app.configuration file to project to store sensitive data.

**Comment by MartyOfMCA** [comment]
https://github.com/EugeneAgyemang/FPIS/pull/53

**Comment by MartyOfMCA** [comment]
The latest commit hash https://github.com/EugeneAgyemang/FPIS/pull/53/commits/a2238e5917c9bb9a60d633e8e11076b4c5e4304 has fixes on:

* The LoginTest.cs to correct bugs that prevented the code from compiling
* Code changes to the Login.cs to make the functions being tested public
* Login service to handle all database operations
* Login service test to test login service functionalities

**Comment by denkyipatrick** [comment]
No more test issues 😄
