### ISSUE TITLE
Create a New Product

### ISSUE THREAD

**Issue by EugeneAgyemang** [EugeneAgyemang/FPIS#5]
A user wants to add a new Product for Analysis.

**Acceptance  Criteria**
Implement the design for add Product UI
Implement the logic to add a new product
Write the necessary unit test

**Implementation Note**
Use a standard design for the UI

**Comment by denkyipatrick** [comment]
Follow the steps below to test the new feature:
* Open the the `Program.cs` file
* Replace `new Main()` in the Main function with `new CreateProductForm()`
* Run `Press 5`
* Enter a product name and click on the `Create Product` button

Test validation features:
* Run the application with the settings above
* Click on `Create Product` with no name
* Observe that an error label is shown under the textbox and an `Error MessageBox` appears

Test existing product
* Run the application with the settings above
* Enter `Reflux` as the product name
* Click on `Create Product`
* Run the application again
* Enter `RefluX` as the product name
* Click on `Create Product`
* Observe that a `MessageBox` appears asking you to change the product name

**Comment by MartyOfMCA** [comment]
Love the clarity. Thanks for the effort!

Adding new product works perfectly 👍
Test validation works perfectly 👍
Test existing product works perfectly 👍

A little extra for everyone:

* Drop the FPIS database first (make sure there're no errors in the **Solution** not just the FPIS project
* Then run `update-database` from the Package Manager Console

That should be it. Thanks!
