### ISSUE TITLE
Update Registration Form

### ISSUE THREAD

**Issue by MartyOfMCA** [EugeneAgyemang/FPIS#7]
The Registration form needs to provide the Designation for the users.

* Add additional field where user would choose their designation

User cannot scroll on the registration page. This can cause the user not being able to click on the register button after providing their details
![Screenshot (7)](https://user-images.githubusercontent.com/104218489/211599054-53053bfb-e0f9-43fb-85dd-f342c39fcb88.png)

**Comment by scottondesign** [comment]
I think the space in between the textboxes ( First name , middle name, last name, password and confirm password ) is too wide. it can be closed a bit in order to eliminate the scroll option.

**Comment by scottondesign** [comment]
The Blue color in the Fuji logo can be used in replace of the background color

**Comment by MartyOfMCA** [comment]
The attached PR has all the code changes.

Changes applied are:

* Merged with fix-interfaces to obtain recent changes to Register form
* Form allows user to provide their designation
